---
# tasks file for roles/httpd
- name: Run HTTPD
  docker_container:
    name: httpd
    image: pepsouille0/discover-docker-httpd:1.0
    networks: 
      - name: prosp_network
    ports: 
      - "80:80"